### PR TITLE
Compuware employee interested in using against vRealize

### PR DESCRIPTION
**Pull request by theuntested**
Hi, Can an example of how to use to revert and or snapshot against vRealize be shared. Have recently began using vRealize 8.2. Moving from vCloud. Thank you. John Allen

### CODE REVIEW

**Comment by prydin** [comment]
I'm not sure I understand the purpose of this PR. Shouldn't this be filed as an issues instead?

**Comment by theuntested** [comment]
Yes. Sorry for that. Is there a way you can give example?

John

**Comment by prydin** [comment]
Yeah, I'm looking into this right now. The trick is that you need to send in a snapshot ID as a parameter. Trying to figure out the best way to obtain a snapshot ID.

**Comment by prydin** [comment]
Opening this as an issue instead.

**Pull request closed without merging**
